LibOfTimetableOfClasses:
  - LibOfTimetableOfClasses/**/*
TimetableOfClasses:
  - TimetableOfClasses/**/*
UnitTestOfTimetableOfClasses:
  - UnitTestOfTimetableOfClasses/**/*
ALARM:
  - **.sln
  - **.csproj
Documentation:
  - **.md
  - **.MD
